# create route table and connect subnet to routes
- name: create route table
  ec2_vpc_route_table:
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ regions }}"
    state: "{{ state }}"
    tags:
      Name: "{{ route_table_name }}"
    subnets: [ "{{ subnet_result.subnet.id }}" ]
    routes:
      - dest: "{{ destinationCidrBlock }}" 
        gateway_id: "{{ igw_result.gateway_id }}"
  register: public_route_table

