- name: create ec2 subnet
  ec2_vpc_subnet:
    vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
    region: "{{ regions }}"
    az: "{{ zone }}"      
    state: "{{ state }}"
    cidr: "{{ subNetCidrBlock }}"
    map_public: yes
    resource_tags:
      Name: "{{ subnet_name }}"
  register: subnet_result
