 - name: create a new ec2 VPC
  # create a vpc with name, cidr block,dns support, and tenancy
   ec2_vpc_net:
    name: "{{ vpc_name }}" 
    cidr_block: "{{ vpcCidrBlock }}"
    region: "{{ regions }}"
    dns_support: yes
    dns_hostnames: yes
    tenancy: default
    state: "{{ state }}"
   register: ec2_vpc_net_result

